#+title: ChemScribe (الكتبة)
#+author: Erik P Almaraz (logoraz)

/A Highly Extensible Chemical Formula Builder with Regulatory Intelligence written in
Common Lisp./

This project is still in the ideation stage - I'm still in the process of determining the
UI system to implement it with. So far my preferences are SDL2, Electron, or GTK.
Also, I am still learning Common Lisp and figured this would be a great way to dive in!

My first goal is to develop a simple database (integrated with JSON), based on CLOS, that can
store/access raw material, formula, and regulatory data types. Second is to develop the
formula builder and project file system manaager UIs.

** Install

  Installing ChemScribe using Guix:

#+begin_src sh

  # Install package dependencies and open sbcl (or clasp)
  $ guix shell -m path/to/chemscribe.scm -- sbcl

  # Or for development...
  $ guix shell -D path/to/chemscribe.scm -- clasp

#+end_src


** Run/Load System

  ChemScribe can be run (at least for now) with the following prescription with sbcl (clasp)
  running:

#+begin_src lisp

  (require :asdf)
  (asdf:load-system :chemscribe)

#+end_src

  I've set it up so it automatically starts slynk so I can connect to it with Emacs. Simply
  connect Emacs Sly to port 4008, via =M-x sly-connect "localhost" 4008=

  Then enter package and start the application to begin hacking!

#+begin_src lisp

  (in-package :chemscribe)

#+end_src


** Clasp

  This section is yet to be developed, but it will stage how to setup clasp to call C++
  utilities for advanced chemical computation features that I plan to implement in this
  application...


** Change Log

*** 0.0.1
   - Initial commit
   - Added basic project scaffold


** References

  - [[https://github.com/lispgames/cl-sdl2][cl-sdl2 (source)]]

  - [[https://github.com/atlas-engineer/cl-electron][cl-electron (source)]]

  - [[https://github.com/bohonghuang/cl-gtk4][cl-gkt4 (source)]]
